name: birthday-reminder
services:
  - name: backend
    type: web
    runtime: python
    region: fra
    git:
      repository: YOUR_GITHUB_REPOSITORY_URL
      branch: main
    build:
      builder: dockerfile
      workdir: birthday_reminder_backend
    ports:
      - port: 8000
        http: "/"
    run:
      command: /app/start.sh
    env:
      - name: DEBUG
        value: "False"
      - name: ALLOWED_HOSTS
        value: "*.koyeb.app,localhost,127.0.0.1"
      - name: CORS_ALLOWED_ORIGINS
        value: "https://brithday-reminder.onrender.com,http://localhost:3000"
      - name: PORT
        value: "8000"
      - name: PYTHONUNBUFFERED
        value: "1" 