services:
  - type: web
    name: birthday-reminder-backend
    env: python
    buildCommand: pip install -r birthday_reminder_backend/requirements.txt
    startCommand: cd birthday_reminder_backend && python manage.py migrate && python manage.py collectstatic --noinput && gunicorn birthday_reminder_backend.wsgi:application --log-file -
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "brithday-reminder-backend.onrender.com,localhost,127.0.0.1"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://brithday-reminder.onrender.com,http://localhost:3000"

  - type: web
    name: birthday-reminder-frontend
    env: static
    buildCommand: cd birthday-reminder-frontend && npm install && npm run build
    staticPublishPath: ./birthday-reminder-frontend/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_VERSION
        value: 18.x 